spring.datasource.url=jdbc:sqlite:finance.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys = ON;
spring.main.web-application-type=none
logging.level.org.springframework.jdbc=DEBUG